"""The SQL safety layer.

Nothing generated by a model reaches Postgres without passing through here, and the
decision is made deterministically on the parsed AST -- never by asking a model whether
its own SQL looks safe. The read-only role stands behind this; neither is sufficient
alone, because a role cannot tell a legitimate aggregate from a table scan of everything
and a validator cannot survive its own bugs.

The rejection suite is inherited from the audited implementation this is adapted from and
extended for a two-schema, insurance-shaped corpus.
"""

from __future__ import annotations

import pytest

from vericlaim.sql.validator import AllowedTable, validate_sql

CLAIMS = AllowedTable(
    schema="ops",
    table="claims",
    columns=("claim_id", "policy_id", "peril", "date_of_loss", "report_date", "incurred_amount"),
)
POLICIES = AllowedTable(
    schema="ops",
    table="policies",
    columns=("policy_id", "plan_name", "region_id"),
)
OPS_REGIONS = AllowedTable(schema="ops", table="regions", columns=("region_id", "region_name"))
# Deliberately shares its bare name with ops.regions: a spreadsheet of the same subject
# is exactly how an ambiguous unqualified reference arises in this corpus.
SHEET_REGIONS = AllowedTable(
    schema="sheets",
    table="regions",
    columns=("region_name", "_workbook", "_sheet", "_row", "_a1_range"),
)
COMPLIANCE = AllowedTable(
    schema="sheets",
    table="inspection_compliance_q1",
    columns=("region_name", "inspection_rate", "_workbook", "_sheet", "_row", "_a1_range"),
)

ALLOWED = (CLAIMS, POLICIES, OPS_REGIONS, COMPLIANCE)


def validate(sql: str, row_limit: int = 50, allowed=ALLOWED):
    return validate_sql(sql, allowed, row_limit)


# --------------------------------------------------------------- what passes


def test_a_select_is_accepted_and_the_row_limit_injected() -> None:
    result = validate("SELECT peril FROM ops.claims")

    assert result.ok, result.reason
    assert "LIMIT 50" in result.sql


def test_a_larger_limit_is_capped_rather_than_rejected() -> None:
    result = validate("SELECT peril FROM ops.claims LIMIT 500")

    assert result.ok, result.reason
    assert "LIMIT 50" in result.sql
    assert "500" not in result.sql


def test_a_cte_is_accepted() -> None:
    sql = """
        WITH water AS (
            SELECT claim_id, peril, incurred_amount FROM ops.claims
        )
        SELECT peril, COUNT(*) AS claim_count
        FROM water
        GROUP BY peril
        ORDER BY claim_count DESC
    """
    result = validate(sql)

    assert result.ok, result.reason
    assert result.sql.startswith("WITH water AS")
    assert result.sql.endswith("LIMIT 50")


def test_a_schema_qualified_star_is_accepted() -> None:
    result = validate("SELECT claims.* FROM ops.claims")

    assert result.ok, result.reason
    assert "LIMIT 50" in result.sql


def test_a_join_across_the_two_schemas_is_accepted() -> None:
    """The spreadsheet source is queryable through the same audited path as the DB."""
    sql = """
        SELECT r.region_name, c.inspection_rate
        FROM ops.regions AS r
        JOIN sheets.inspection_compliance_q1 AS c ON c.region_name = r.region_name
    """
    result = validate(sql)

    assert result.ok, result.reason


def test_a_lateral_values_source_beside_an_allowed_table_is_accepted() -> None:
    sql = """
        SELECT claims.peril, constants.marker
        FROM ops.claims
        CROSS JOIN LATERAL (VALUES (1)) AS constants(marker)
    """
    result = validate(sql)

    assert result.ok, result.reason


def test_a_correlated_exists_is_accepted() -> None:
    sql = """
        SELECT c.claim_id
        FROM ops.claims AS c
        WHERE EXISTS (
            SELECT 1 FROM ops.policies AS p WHERE p.policy_id = c.policy_id
        )
    """
    result = validate(sql)

    assert result.ok, result.reason
    assert "EXISTS" in result.sql


def test_an_in_subquery_is_accepted() -> None:
    sql = """
        SELECT c.claim_id
        FROM ops.claims AS c
        WHERE c.policy_id IN (SELECT p.policy_id FROM ops.policies AS p)
    """
    result = validate(sql)

    assert result.ok, result.reason
    assert " IN " in result.sql


# ------------------------------------------------------------- set operations


@pytest.mark.parametrize("operator", ["UNION", "UNION ALL", "INTERSECT", "EXCEPT"])
def test_a_set_operation_over_allowed_tables_is_accepted(operator: str) -> None:
    """The deliberate relaxation.

    The implementation this is adapted from admits only a bare SELECT, which is right for
    one table per question and wrong here: "water-damage claims and the policies covering
    them" is naturally a union across claim types, and rejecting it would push the repair
    loop into rewriting correct SQL.
    """
    sql = (
        f"SELECT claim_id FROM ops.claims WHERE peril = 'water' {operator} "
        "SELECT claim_id FROM ops.claims WHERE peril = 'fire'"
    )
    result = validate(sql)

    assert result.ok, result.reason
    assert "LIMIT 50" in result.sql


def test_a_set_operation_is_still_allow_listed_leg_by_leg() -> None:
    """Relaxing the statement gate must not open a side door for a forbidden table."""
    sql = (
        "SELECT claim_id FROM ops.claims UNION SELECT id FROM ops.audit_log"
    )
    result = validate(sql)

    assert not result.ok
    assert "audit_log" in result.reason


def test_a_set_operation_reports_every_table_it_touches() -> None:
    sql = "SELECT policy_id FROM ops.claims UNION SELECT policy_id FROM ops.policies"
    result = validate(sql)

    assert result.ok, result.reason
    assert result.tables == ("ops.claims", "ops.policies")


# ----------------------------------------------------- unqualified references


def test_an_unqualified_table_is_resolved_and_normalized() -> None:
    """A model that omits the schema gets a qualified rewrite, not a rejection.

    The normalized SQL is what gets executed and cited, so leaving it schema-less would
    make the citation depend on the session's search_path.
    """
    result = validate("SELECT peril FROM claims")

    assert result.ok, result.reason
    assert "ops.claims" in result.sql
    assert result.tables == ("ops.claims",)


def test_an_ambiguous_unqualified_table_is_rejected_by_name() -> None:
    """`regions` exists in both schemas; guessing one would silently answer from the
    wrong source."""
    result = validate("SELECT region_name FROM regions", allowed=(*ALLOWED, SHEET_REGIONS))

    assert not result.ok
    assert "ambiguous" in result.reason.lower()
    assert "ops.regions" in result.reason
    assert "sheets.regions" in result.reason


# --------------------------------------------------------------- what is rejected


@pytest.mark.parametrize(
    "sql, expected_reason",
    [
        ("DROP TABLE ops.claims", "Only SELECT"),
        ("UPDATE ops.claims SET peril = 'x'", "Only SELECT"),
        ("INSERT INTO ops.claims (peril) VALUES ('x')", "Only SELECT"),
        ("DELETE FROM ops.claims", "Only SELECT"),
        ("TRUNCATE ops.claims", "Only SELECT"),
        ("GRANT SELECT ON ops.claims TO PUBLIC", "Only SELECT"),
        ("SELECT peril FROM ops.claims; SELECT claim_id FROM ops.claims", "Exactly one"),
        ("SELECT peril FROM ops.reserves_internal", "Table is not allowed"),
        ("SELECT hallucinated FROM ops.claims", "Column validation failed"),
        ("SELECT * FROM information_schema.tables", "Schema is not allowed"),
        ("SELECT * FROM pg_catalog.pg_user", "Schema is not allowed"),
        ("SELECT peril FROM other.ops.claims", "Catalog is not allowed"),
        ("SELECT *", "requires an allowed source table"),
        ("SELECT set_config('search_path', 'public', false)", "allowed table"),
        ("SELECT pg_sleep(1)", "allowed table"),
        ("SELECT current_setting('is_superuser')", "allowed table"),
        ("SELECT peril INTO copied FROM ops.claims", "DDL and DML"),
        ("SELECT peril FROM ops.claims FOR UPDATE", "locking"),
        ("SELECT peril FROM ops.claims WHERE", "SQL parse error"),
    ],
    ids=[
        "drop",
        "update",
        "insert",
        "delete",
        "truncate",
        "grant",
        "multi-statement",
        "unlisted-table",
        "hallucinated-column",
        "information-schema",
        "pg-catalog",
        "catalog-escape",
        "bare-star",
        "set-config",
        "pg-sleep",
        "current-setting",
        "select-into",
        "for-update",
        "malformed",
    ],
)
def test_unsafe_sql_is_rejected(sql: str, expected_reason: str) -> None:
    result = validate(sql)

    assert not result.ok
    assert expected_reason in result.reason
    assert result.sql == ""


@pytest.mark.parametrize(
    "sql",
    [
        """
        SELECT c.claim_id
        FROM ops.claims AS c
        WHERE EXISTS (SELECT 1 FROM ops.policies AS p WHERE p.plan_name = 'HomeSecure')
        """,
        """
        SELECT c.claim_id
        FROM ops.claims AS c
        WHERE NOT EXISTS (SELECT 1 FROM ops.policies AS p WHERE p.plan_name = 'HomeSecure')
        """,
    ],
    ids=["exists", "not-exists"],
)
def test_an_uncorrelated_exists_is_rejected(sql: str) -> None:
    """Row-independent: it cannot express the restriction the question asked for."""
    result = validate(sql)

    assert not result.ok
    assert "Uncorrelated EXISTS" in result.reason


def test_a_non_literal_limit_is_rejected() -> None:
    result = validate("SELECT peril FROM ops.claims LIMIT (SELECT claim_id FROM ops.claims)")

    assert not result.ok
    assert result.reason == "LIMIT must be an integer literal"


def test_a_negative_limit_is_rejected() -> None:
    result = validate("SELECT peril FROM ops.claims LIMIT -1")

    assert not result.ok
    assert "negative" in result.reason


# ------------------------------------------------------- the allow-list itself


def test_an_empty_allow_list_rejects_everything() -> None:
    """Fails closed: a caller that forgot to select contexts gets nothing executed."""
    result = validate("SELECT peril FROM ops.claims", allowed=())

    assert not result.ok
    assert "No tables are allowed" in result.reason


@pytest.mark.parametrize("row_limit", [0, -5, "50", True], ids=["zero", "negative", "str", "bool"])
def test_a_nonsensical_row_limit_is_rejected(row_limit) -> None:
    result = validate("SELECT peril FROM ops.claims", row_limit=row_limit)

    assert not result.ok
    assert "Row limit" in result.reason


def test_the_allow_list_is_case_insensitive() -> None:
    result = validate("SELECT PERIL FROM OPS.CLAIMS")

    assert result.ok, result.reason


def test_a_rejected_statement_never_returns_sql() -> None:
    """The repair loop reads .sql; returning normalized text beside a rejection would
    invite executing it."""
    result = validate("SELECT peril FROM ops.reserves_internal")

    assert result.sql == ""
    assert result.tables == ()


def test_prose_that_opens_a_quote_is_rejected_rather_than_raised() -> None:
    """sqlglot signals an unterminated quote with TokenError, which is a *sibling* of
    ParseError rather than a subclass. A model that emits prose instead of SQL -- "the
    adjuster's base region" -- produces exactly that, so a handler written for
    ParseError alone lets it escape the bounded repair loop and kill the whole source.
    The validator must fail closed here, not raise.
    """
    result = validate("SELECT region FROM ops.claims WHERE x = the adjuster's base region")

    assert not result.ok
    assert "parse error" in result.reason.lower()
    assert result.sql == ""
